package day21;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class AlertsDemo {

    /*
     * =====================================================================================
     *  SELENIUM ALERTS — COMPLETE CONCEPT GUIDE (Java + TestNG friendly)
     * =====================================================================================
     *  This file explains every concept around handling JavaScript Alerts/Popups in
     *  Selenium WebDriver, step by step, with runnable code and interview Q&A embedded
     *  as comments at the end of each section.
     * =====================================================================================
     */

    public static void main(String[] args) throws InterruptedException {

        WebDriver driver = new ChromeDriver();
        driver.get("https://rahulshettyacademy.com/AutomationPractice/");
        driver.manage().window().maximize();

        /*
         * =================================================================================
         * STEP 1: WHAT IS AN ALERT IN SELENIUM?
         * =================================================================================
         * An "Alert" is a small pop-up box generated by JavaScript (window.alert(),
         * window.confirm(), window.prompt()) that appears ON TOP of the browser window.
         *
         * IMPORTANT: Alerts are NOT part of the HTML DOM. That's why you CANNOT locate
         * them using By.id(), By.xpath(), findElement(), etc. They live at the browser
         * (OS-window) level, so Selenium needs a special API to interact with them:
         *      driver.switchTo().alert()
         *
         * -------------------------------------------------------------------------------
         * Q1: Why can't we use normal locators (findElement) to handle a JS alert?
         * A1: Because an alert is a native browser-level UI component rendered outside
         *     the HTML DOM tree. Selenium's element-locating strategies only work within
         *     the DOM, so alerts require the driver.switchTo().alert() API instead.
         * -------------------------------------------------------------------------------
         */


        /*
         * =================================================================================
         * STEP 2: TYPES OF ALERTS
         * =================================================================================
         * There are 3 types of JavaScript alerts you'll encounter:
         *
         * 1) SIMPLE ALERT       -> window.alert("message")
         *    - Has only an "OK" button.
         *    - Used to show information/warning to the user.
         *
         * 2) CONFIRMATION ALERT -> window.confirm("message")
         *    - Has "OK" and "Cancel" buttons.
         *    - Used to confirm an action (e.g., "Are you sure you want to delete?").
         *
         * 3) PROMPT ALERT       -> window.prompt("message", "defaultText")
         *    - Has an input text box along with "OK" and "Cancel" buttons.
         *    - Used to take small text input from the user (e.g., "Enter your name").
         *
         * -------------------------------------------------------------------------------
         * Q2: What are the different types of alerts in Selenium?
         * A2: Simple Alert (OK only), Confirmation Alert (OK/Cancel), and Prompt Alert
         *     (text box + OK/Cancel). Selenium handles all three via the same Alert
         *     interface, just using different methods (accept/dismiss/sendKeys).
         * -------------------------------------------------------------------------------
         */


        /*
         * =================================================================================
         * STEP 3: SWITCHING TO AN ALERT
         * =================================================================================
         * Before you can interact with an alert, you MUST switch the driver's focus to it.
         * This is done using:
         *
         *      Alert alert = driver.switchTo().alert();
         *
         * This returns an object of type org.openqa.selenium.Alert, which exposes methods
         * to accept, dismiss, read text from, or type into the alert.
         *
         * -------------------------------------------------------------------------------
         * Q3: What does driver.switchTo().alert() return, and why is it needed?
         * A3: It returns an Alert object representing the currently active JS popup.
         *     It's needed because Selenium's WebDriver focus stays on the main browser
         *     window/DOM by default; switchTo() shifts control explicitly to the alert
         *     so subsequent commands (accept/dismiss/getText) act on it.
         * -------------------------------------------------------------------------------
         */
        String  text = "Hari";
        driver.findElement(By.cssSelector("#name")).sendKeys(text);
        driver.findElement(By.id("alertbtn")).click();

        System.out.println(driver.switchTo().alert().getText());
        driver.switchTo().alert().accept();



        /*
         * =================================================================================
         * STEP 4: CORE ALERT METHODS (THE ALERT INTERFACE)
         * =================================================================================
         * The Alert interface provides 4 main methods:
         *
         * 1) alert.accept()
         *      - Clicks "OK" button.
         *      - For simple alerts, this is the only way to close them.
         *
         * 2) alert.dismiss()
         *      - Clicks "Cancel" button (or closes the alert without accepting).
         *      - For simple alerts (no Cancel button), dismiss() behaves like closing
         *        the alert (same effect as accept() in most drivers, but avoid relying
         *        on this — use accept() for simple alerts).
         *
         * 3) alert.getText()
         *      - Returns the message text displayed inside the alert box.
         *      - Useful for assertions, e.g., verifying the correct warning is shown.
         *
         * 4) alert.sendKeys("text")
         *      - Types text into a PROMPT alert's input box.
         *      - Throws ElementNotInteractableException if used on simple/confirm alerts
         *        (since they have no input box).
         *
         * -------------------------------------------------------------------------------
         * Q4: What's the difference between accept() and dismiss()?
         * A4: accept() clicks OK (positive action); dismiss() clicks Cancel or closes the
         *     alert (negative/neutral action). On a simple alert (OK-only), dismiss()
         *     still closes it, but best practice is to always use accept() there since
         *     there's conceptually no "cancel" action.
         *
         * Q5: How do you retrieve the message displayed in an alert box?
         * A5: alert.getText() — returns the alert's message as a String, which can then
         *     be used in assertions.
         *
         * Q6: How do you enter text into a prompt alert?
         * A6: alert.sendKeys("your text") followed by alert.accept() to submit it.
         * -------------------------------------------------------------------------------
         */
            Thread.sleep(2000);
            driver.findElement(By.cssSelector("[value='Confirm']")).click();
            System.out.println(driver.switchTo().alert().getText());
            driver.switchTo().alert().accept();

            //Then Comes the prompt alert that we have to enter some text in the alert ,
            // and click on ok or cancel it depends

        driver.quit();

        /*
         * =================================================================================
         * STEP 5: HANDLING ALERTS THAT TAKE TIME TO APPEAR (EXPLICIT WAIT)
         * =================================================================================
         * If an alert appears after some delay (e.g., triggered by an AJAX call or a
         * setTimeout in JS), calling switchTo().alert() immediately will throw:
         *      NoAlertPresentException
         *
         * SOLUTION: Use WebDriverWait with ExpectedConditions.alertIsPresent()
         *
         * -------------------------------------------------------------------------------
         * Q7: How do you handle an alert that doesn't appear immediately?
         * A7: Use an explicit wait:
         *     new WebDriverWait(driver, Duration.ofSeconds(10))
         *         .until(ExpectedConditions.alertIsPresent());
         *     This polls until the alert appears, avoiding NoAlertPresentException,
         *     instead of using Thread.sleep() which is unreliable and slow.
         * -------------------------------------------------------------------------------
         */
        /*
        public void demoWaitForAlert() {
            driver.findElement(By.id("delayedAlertBtn")).click();
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
            Alert alert = wait.until(ExpectedConditions.alertIsPresent());
            alert.accept();
        }
        */

        /*
         * =================================================================================
         * STEP 6: EXCEPTIONS RELATED TO ALERTS
         * =================================================================================
         * 1) NoAlertPresentException
         *      - Thrown when you call switchTo().alert() but no alert is currently open.
         *
         * 2) UnhandledAlertException
         *      - Thrown when Selenium tries to perform an operation (like click() or
         *        navigate) on the page while an alert is still open and unhandled.
         *        Some browsers auto-dismiss the alert when this happens.
         *
         * BEST PRACTICE: Always handle (accept/dismiss) an alert as soon as it appears,
         * before doing anything else with the driver.
         *
         * -------------------------------------------------------------------------------
         * Q8: What exception do you get if you try to switch to an alert that isn't there?
         * A8: org.openqa.selenium.NoAlertPresentException.
         *
         * Q9: What happens if an alert is open and you try to interact with the page?
         * A9: You get an UnhandledAlertException (behavior can vary slightly by browser/
         *     driver version) — Selenium blocks other commands until the alert is
         *     handled because the alert has native OS-level focus.
         * -------------------------------------------------------------------------------
         */

        /*
         * =================================================================================
         * STEP 7: HANDLING UNEXPECTED ALERTS AUTOMATICALLY (DRIVER CAPABILITY)
         * =================================================================================
         * You can configure how the browser driver behaves when it hits an unexpected
         * alert during a command, using UnexpectedAlertBehaviour (mostly relevant with
         * older RemoteWebDriver/DesiredCapabilities setups, or ChromeOptions in newer
         * versions):
         *      - ACCEPT              -> auto-accepts unexpected alerts
         *      - DISMISS              -> auto-dismisses unexpected alerts
         *      - IGNORE                -> leaves alert open, throws exception on next command
         *      - ACCEPT_AND_NOTIFY  -> accepts + throws UnhandledAlertException
         *      - DISMISS_AND_NOTIFY -> dismisses + throws UnhandledAlertException
         *
         * -------------------------------------------------------------------------------
         * Q10: How can Selenium automatically handle unexpected/unplanned alerts?
         * A10: By setting the "unhandledPromptBehavior" capability (e.g., via
         *      ChromeOptions.setCapability or DesiredCapabilities) to a value like
         *      "accept", "dismiss", or "ignore" — this tells the driver how to react
         *      when it encounters an alert it wasn't explicitly told to handle.
         * -------------------------------------------------------------------------------
         */


        /*
         * =================================================================================
         * STEP 8: PUTTING IT ALL TOGETHER — A REALISTIC TEST FLOW
         * =================================================================================
         */


        /*
         * =================================================================================
         * BONUS: QUICK-FIRE INTERVIEW Q&A
         * =================================================================================
         *
         * Q11: Can we use Actions class or Robot class to handle Selenium web alerts?
         * A11: Actions class - NO, it only works within the DOM. Robot class (java.awt) -
         *      technically YES since it simulates real OS-level keyboard/mouse events
         *      (e.g., pressing Enter to accept), but it's discouraged because it's
         *      unreliable, not cross-platform-friendly, and depends on window focus.
         *      The Alert interface (switchTo().alert()) is the correct, standard approach.
         *
         * Q12: Does Selenium support handling Windows-based (native OS) popups/dialogs,
         *      like a file-upload dialog or authentication popup?
         * A12: No. WebDriver's Alert interface only handles JAVASCRIPT-generated alerts
         *      (alert/confirm/prompt). Native OS dialogs (file upload windows, Windows
         *      authentication popups) are NOT part of the browser and need external
         *      tools like Robot class, AutoIT, Sikuli, or (for file uploads) simply
         *      sendKeys() to the hidden <input type="file"> element, which avoids the
         *      OS dialog entirely.
         *
         * Q13: How do you handle basic HTTP authentication popups in Selenium?
         * A13: Pass credentials directly in the URL:
         *      driver.get("https://username:password@example.com");
         *      This bypasses the native browser auth dialog entirely.
         *
         * Q14: If multiple alerts are triggered one after another, how do you handle them?
         * A14: Handle them one at a time in a loop/sequence — switch to the alert,
         *      accept/dismiss it, then the next alert (if any) becomes accessible.
         *      You cannot access a second alert until the first is handled.
         *
         * Q15: Is Alert handling part of WebDriver's core interface or a separate class?
         * A15: Alert is a separate interface (org.openqa.selenium.Alert) obtained via
         *      the TargetLocator interface's alert() method — i.e.
         *      driver.switchTo() returns a TargetLocator, and .alert() on that returns
         *      the Alert object.
         * =================================================================================
         */


    }
}
